# Generated by Django 5.1.7 on 2025-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(through='app.TaskAssignment', to='app.user'),
        ),
    ]
