# Generated by Django 5.1.7 on 2025-03-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set(),
        ),
    ]
